config/routes.rb
Rails.application.routes.draw do
  
  #devise_for :users
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  
  root 'home#index'
  get 'home/index'
  get 'activity', to: 'home#activity'
  get 'analytics', to: 'home#analytics'
  get 'privacy_policy', to: 'home#privacy_policy'
  
  
  resources :enrollments do 
    get :my_students, on: :collection
    member do 
      get :certificate
    end
  end
  
  resources :tags, only: [:create, :index, :destroy]
  resources :courses do
    get :purchased, :pending_review, :created, :unapproved, on: :collection
    member do 
      get :analytics
      patch :approve
      patch :unapprove
    end
    resources :lessons, escept: [:index] do 
      resources :comments, escept: [:index]
      put :sort 
      member do 
        delete :delete_video
      end
    end
    resources :enrollments, only: [:new, :create]
    resources :course_wizard, controller: 'courses/course_wizard'
  end
  
  
  resources :users, only: [:index, :edit, :show, :update]

  resources :youtube, only: :show
  
  namespace :charts do 
    get 'users_per_day'
    get 'enrollments_per_day'
    get 'course_popularity'
    get 'money_makers'
  end 
  #get 'charts/users_per_day', to: 'charts#users_per_day'
  #get 'charts/enrollments_per_day', to: 'charts#enrollments_per_day'
  #get 'charts/course_popularity', to: 'charts#course_popularity'
  #get 'charts/money_makers', to: 'charts#money_makers'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, :only => [ :index, :privacy_policy ]
  def index
    #@courses = Course.all.limit(3)
    @latest_good_reviews = Enrollment.reviewed.latest_good_reviews
    @latest = Course.latest.published.approved
    @top_rated = Course.top_rated.published.approved
    @popular = Course.popular.published.approved
    if current_user
      @purchased_courses = Course.joins(:enrollments).where(enrollments: {user: current_user}).order(created_at: :desc).limit(3)
      @created_courses = current_user.courses
    end
    @popular_tags = Tag.all.where.not(course_tags_count: 0).order(course_tags_count: :desc).limit(10)
  end

  def activity
    if current_user.has_role?(:admin)
      @pagy, @activities = pagy(PublicActivity::Activity.all.order(created_at: :desc))
    else 
      redirect_to root_path, alert: "You are not authorized to access that page."
    end
  end

  def analytics 
    if current_user.has_role?(:admin)
      #@users = User.all
      #@enrollments = Enrollment.all
      #@courses = Course.all
    else 
      redirect_to root_path, alert: "You are not authorized to access that page."
    end
  end

  def privacy_policy

  end
end

app/views/home/activity.html.haml
- content_for :title do 
  Judo2000 
  \|
  Activity

%h3
  .text-center
    Activity 
    .badge.badge-info 
      = @activities.count 
%p
%ul.list-group
  - @activities.each do |activity|
    %li.list-group-item
      /= activity.id
      = activity.created_at.strftime('%m-%d-%Y - %H:%m')
      (#{time_ago_in_words(activity.created_at)} ago)
      /= activity.trackable_type
      = model_label(activity.trackable_type)
      /= activity.trackable_id
      - if activity.trackable_type == 'Lesson'
        - if Lesson.where(id: activity.trackable_id).present? 
          = link_to activity.trackable.content, course_lesson_path(activity.trackable.course, activity.trackable)
          /= link_to activity.trackable, course_lesson_path(activity.trackable.course, activity.trackable)
        - else 
          Lesson was deleted
      - elsif activity.trackable_type == 'Comment' 
        - if Comment.where(id: activity.trackable_id).present?
          = link_to activity.trackable, course_lesson_path(activity.trackable.lesson.course, activity.trackable.lesson)
        - else 
          Comment was deleted
      - else
        = link_to activity.trackable, activity.trackable 
      = activity.key
      = crud_label(activity.key.match(/\.(.*)/)[1])
      By 
      - if activity.owner.present?
        = link_to activity.owner, user_path(activity.owner)
        - if activity.parameters.any?
          = activity.parameters
      - else
        a deleted user
!= pagy_bootstrap_nav(@pagy)
%br

app/views/home/analytics.html.haml
%h4
  Users Created
/= line_chart @users.group_by_day(:created_at).count
= line_chart charts_users_per_day_path 

%h4
  Enrollments created per day
/= column_chart @enrollments.group_by_day(:created_at).count
= column_chart charts_enrollments_per_day_path

%h4 
  Course Popularity 
-# = pie_chart @courses.group(:enrollments_count).count
-#= pie_chart @enrollments.joins(:course).group(:'courses.title').count
= bar_chart charts_course_popularity_path

%h4 
  Most paid courses 
= bar_chart charts_money_makers_path

app/views/home/index.html.haml
- content_for :title do 
  Judo2000 
  \|
  Ruby Gems Startup

.jumbotron
  .display-4
    What do you want to learn today?
  
  .p-4
  - if current_user
    = search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f|
      .input-group
        = f.search_field :title_cont, class: 'form-control-sm', style: 'float: left; width: 150px; ', placeholder: 'Find a course', :autocomplete => :off
        %span.input-group-append
          %button.btn.btn-primary.btn-sm{:type => "submit"}
            %span.fa.fa-search{"aria-hidden" => "true"}   

  -else
    %h3.text-shadow Join to access all the courses
    .p-2
    = link_to 'Register', new_user_registration_path, class: 'btn btn-custompurple btn-lg'
    = link_to 'Login', new_user_session_path, class: 'btn btn-custompurple btn-lg'
    .row.mt-1
    = link_to user_google_oauth2_omniauth_authorize_path, class: 'btn btn-danger btn-lg mr-1', method: :post do
      Continue with
      .fab.fa-google
    .row.mt-1
    = link_to user_github_omniauth_authorize_path, class: 'btn btn-dark btn-lg mr-1', method: :post do
      Continue with
      .fab.fa-github
    .row.mt-1
    = link_to user_facebook_omniauth_authorize_path, class: 'btn btn-primary btn-lg mr-1', method: :post do
      Continue with
      .fab.fa-facebook
.card-group 
  .card.card-body 
    %h1 
      .fa.fa-graduation-cap 
    = Course.count 
    online courses
    .row 
    Explore a variety of topics 
  .card.card-body 
    %h1 
      .fa.fa-chalkboard-teacher 
    = Course.distinct.count(:user_id)
    expert instructors 
    .row 
    Find the right instructor for you
  .card.card-body 
    %h1 
      .fa.fa-user-graduate 
    = User.count 
    active learners 
    .row 
    Join knowledge sharing community 
  .card.card-body 
    %h1 
      .fa.fa-infinity 
    Lifetime %access 
    .row 
    Learn on your schedule 

%hr
- if current_user
  %h2
    .fa.fa-user-graduate
    Continue learning 
  .card-columns 
    - @purchased_courses.each do |course|
      = render 'courses/course', course: course
  .text-right
    = link_to 'See all my purchased courses', purchased_courses_path
  %hr
%h2
  .fa.fa-chart-line
  Popular courses 
.card-columns 
  - @popular.each do |course|
    = render 'courses/course', course: course
.text-right
  = link_to 'More popular courses', courses_path(courses_search: {s: 'enrollment_count des' })
%hr
%h2
  .fa.fa-star
  Top rated courses 
.card-columns 
  - @top_rated.each do |course|
    = render 'courses/course', course: course
.text-right
  = link_to 'Best rated courses', courses_path(courses_search: {s: 'rating des' })
%hr
%h2
  .fa.fa-clock
  Latest courses 
.card-columns 
  - @latest.each do |course|
    = render 'courses/course', course: course
.text-right
  = link_to 'Most recent courses', courses_path(courses_search: {s: 'created_at des' })
%hr
%h2
  .fa.fa-tags
  Most Popular Tags 
- @popular_tags.all.each do |tag|
  = link_to courses_path(courses_search: {course_tags_tag_id_eq: tag.id}) do
    .badge.badge-info 
      %h4
        = tag.name 
        = tag.course_tags_count
  
%hr
%h2
  .fa.fa-comment
  What our students have to say
.card-columns 
  - @latest_good_reviews.each do |enrollment|
    = render 'enrollments/enrollment', enrollment: enrollment

app/views/home/privacy_policy.html.haml
%h2 Privacy Policy
%p
  Your privacy is important to us. It is Corsego's policy to respect your privacy regarding any information we may collect from you across our website,
  = succeed "," do
    %a{:href => "https://judo2000-ruby-startup.herokuapp.com"} http://corsego.com
%p We only ask for personal information when we truly need it to provide a service to you. We collect it by fair and lawful means, with your knowledge and consent. We also let you know why we’re collecting it and how it will be used.
%p We only retain collected information for as long as necessary to provide you with your requested service. What data we store, we’ll protect within commercially acceptable means to prevent loss and theft, as well as unauthorized access, disclosure, copying, use or modification.
%p We don’t share any personally identifying information publicly or with third-parties, except when required to by law.
%p Our website may link to external sites that are not operated by us. Please be aware that we have no control over the content and practices of these sites, and cannot accept responsibility or liability for their respective privacy policies.
%p You are free to refuse our request for your personal information, with the understanding that we may be unable to provide you with some of your desired services.
%p Your continued use of our website will be regarded as acceptance of our practices around privacy and personal information. If you have any questions about how we handle user data and personal information, feel free to contact us.
%p This policy is effective as of 24 April 2020.