config/routes.rb
Rails.application.routes.draw do
  
  #devise_for :users
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  
  root 'home#index'
  get 'home/index'
  get 'activity', to: 'home#activity'
  get 'analytics', to: 'home#analytics'
  get 'privacy_policy', to: 'home#privacy_policy'
  
  
  resources :enrollments do 
    get :my_students, on: :collection
    member do 
      get :certificate
    end
  end
  
  resources :tags, only: [:create, :index, :destroy]
  resources :courses do
    get :purchased, :pending_review, :created, :unapproved, on: :collection
    member do 
      get :analytics
      patch :approve
      patch :unapprove
    end
    resources :lessons, escept: [:index] do 
      resources :comments, escept: [:index]
      put :sort 
      member do 
        delete :delete_video
      end
    end
    resources :enrollments, only: [:new, :create]
    resources :course_wizard, controller: 'courses/course_wizard'
  end
  
  
  resources :users, only: [:index, :edit, :show, :update]

  resources :youtube, only: :show
  
  namespace :charts do 
    get 'users_per_day'
    get 'enrollments_per_day'
    get 'course_popularity'
    get 'money_makers'
  end 
  #get 'charts/users_per_day', to: 'charts#users_per_day'
  #get 'charts/enrollments_per_day', to: 'charts#enrollments_per_day'
  #get 'charts/course_popularity', to: 'charts#course_popularity'
  #get 'charts/money_makers', to: 'charts#money_makers'
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course, counter_cache: true
  has_many :user_lessons, dependent: :destroy
  has_many :comments, dependent: :nullify

  #Course.find_each { |course| Course.reset_counters(course.id, :lessons) }
  validates :title, :content, :course, presence: true
  validates :title, length: { :maximum => 70 }
  validates_uniqueness_of :title, scope: :course_id
  has_rich_text :content
  mount_uploader :video, VideoUploader
  mount_uploader :thumbnail, ThumbnailUploader
  
  #validates :thumbnail, presence: true, if: :video_present?
  def video_present?
    self.video.present?
  end
  
  extend FriendlyId
  friendly_id :title, use: :slugged

  include PublicActivity::Model
  tracked owner: Proc.new{ |controller, model| controller.current_user }

  include RankedModel
  ranks :row_order, with_same: :course_id

  def to_s
    title
  end

  def prev 
    course.lessons.where("row_order < ?", row_order).order(:row_order).last
  end

  def next 
    course.lessons.where("row_order > ?", row_order).order(:row_order).first
  end

  def viewed(user)
    self.user_lessons.where(user: user).present?
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: %i[ show edit update destroy delete_video ]

  def delete_video 
    authorize @lesson, :edit? 
    if @lesson.video
      @video = @lesson.video 
      @video.remove!
      @lesson.video = ''
      @lesson.save
    end
    if @lesson.thumbnail
      @thumbnail = @lesson.thumbnail 
      @thumbnail.remove!
      @lesson.thumbnail = ''
      @lesson.save
    end
    redirect_to edit_course_lesson_path(@course, @lesson), notice: "Video successfully deleted"

  end

  def sort
    @course = Course.friendly.find(params[:course_id])
    lesson = Lesson.friendly.find(params[:lesson_id])
    authorize lesson, :edit?
    lesson.update(lesson_params)
    render body: nil
  end

  def index
    @lessons = Lesson.all
  end

  def show
    authorize @lesson
    current_user.view_lesson(@lesson)
    @lessons = @course.lessons.rank(:row_order)
    @comment = Comment.new
    @comments = @lesson.comments.order(created_at: :desc)
  end

  def new
    @lesson = Lesson.new
    @course = Course.friendly.find(params[:course_id])

  end

  def edit
    authorize @lesson
  end

  def create
    @lesson = Lesson.new(lesson_params)
    @course = Course.friendly.find(params[:course_id])
    @lesson.course_id = @course.id
    authorize @lesson
    respond_to do |format|
      if @lesson.save
        format.html { redirect_to course_lesson_path(@course, @lesson), notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @lesson
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to course_lesson_path(@course, @lesson), notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @lesson
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to course_path(@course), notice: "Lesson was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_lesson
      @course = Course.friendly.find(params[:course_id])
      @lesson = Lesson.friendly.find(params[:id])
    end

    def lesson_params
      params.require(:lesson).permit(:title, :content, :row_order_position, :video, :thumbnail)
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.haml
-# frozen_string_literal: true
= simple_form_for([@course, @lesson]) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title, input_html: { autocomplete: 'off' }
    = f.input :content, as: :rich_text_area
    -# = f.label :content
    -# = f.rich_text_area  :content
    -# %small= f.error :content, class: 'text-danger'
    %p
    - if @lesson.video.present?
      - video_filename = @lesson.video.url.split('https://nyc3.digitaloceanspaces.com/judo/uploads/lesson/video/')[1]
      = video_filename
      = link_to "Remove video and thumbnail", delete_video_course_lesson_path(@course, @lesson), method: :delete, data: { confirm: 'Are you sure?' }
    = f.input :video 
    - if @lesson.thumbnail.present?
      - thumbnail_filename = @lesson.thumbnail.url.split('https://nyc3.digitaloceanspaces.com/judo/uploads/lesson/thumbnail/')[1]
      = thumbnail_filename
    = f.input :thumbnail
    /= f.input :content
    /= f.association :course
    /= f.input :course_id, input_html: {value: @lesson.course_id || params[:course_id]}, as: :hidden
  .form-actions
    = f.button :submit

app/views/lessons/_lesson.html.haml
.card
  .card-header
    - if lesson.viewed(current_user) == true
      .text-success.fa.fa-check-square
      /VIEWED
    - else
      .text-danger.fa.fa-check-square
      /NOT VIEWED
    /.far.fa-check-square
    = link_to course_lesson_path(@course, lesson) do
      %b
        #{lesson.row_order_rank + 1}.
      = lesson.title
  /- if policy(lesson).show?
  .card-body
    - if @lesson.video.present?
      - if @lesson.thumbnail.present?
        %video(controls="true" poster="#{url_for @lesson.thumbnail.url}" width="100%" preload="metadata" controlslist="nodownload")
          %source{src: @lesson.video.url, type:"#{@lesson.video.content_type}"}
        -# = content_tag :video, id: 'my-video', poster: @lesson.thumbnail.url do
        -#   = tag :source, src: @lesson.video.url, type: @lesson.video.content_type
      - else 
        %video(controls="true" width="100%" preload="metadata" controlslist="nodownload")
          %source{src: @lesson.video.url, type:"#{@lesson.video.content_type}"}
        -# = content_tag :video, id: 'my-video' do
        -#   = tag :source, src: @lesson.video.url, type: @lesson.video.content_type
    %p
    = lesson.content
  - if policy(lesson).edit?
    .card-footer
      = link_to 'Edit', edit_course_lesson_path(@course, lesson), class: 'btn btn-sm btn-warning'
      = link_to 'Destroy', [@course, lesson], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger'
  .card-footer
    - unless lesson.prev.nil?
      .float-left
        = link_to course_lesson_path(@course, lesson.prev), class: 'btn btn-sm btn-info' do
          .fa.fa-arrow-left
          Previous
    - unless lesson.next.nil?
      .float-right
        = link_to course_lesson_path(@course, lesson.next), class: 'btn btn-sm btn-info' do
          .fa.fa-arrow-right
          Next

app/views/lessons/_lesson_preview.html.haml
- if current_user
  /- if lesson.course.bought(current_user) || @course.user == current_user
  - if policy(lesson).show?
    - if lesson.viewed(current_user) == true
      .text-success.fa.fa-check-square
    - else
      .text-danger.fa.fa-check-square
  - else
    .fa.fa-check-square
  = link_to course_lesson_path(@course, lesson) do 
    /= lesson.row_order
    %b
      #{lesson.row_order_rank + 1}.
    = lesson.title
- else
  .fa.fa-check-square
  = link_to course_lesson_path(@course, lesson) do 
    /= lesson.row_order
    %b
      #{lesson.row_order_rank + 1}.
    = lesson.title
.col-md-5
  %small
    .fa.fa-comment
    = lesson.comments_count
    - if policy(lesson).edit?
      .fa.fa-eye
      Viewers:
      /= lesson.user_lessons.count
      = lesson.user_lessons_count
      .fa.fa-eye
      Impressions:
      = lesson.user_lessons.map(&:impressions).sum
    .row
    = link_to 'Edit', edit_course_lesson_path(@course, lesson), class: 'btn btn-sm btn-warning'
    = link_to 'Destroy', [@course, lesson], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger'

app/views/lessons/edit.html.haml
- content_for :title do 
  Judo2000 
  \/
  Course
  = @course.title 
  \/
  Editing lesson 
  = @lesson.title

= link_to 'Courses', courses_path
\/
= link_to @lesson.course.title, course_path(@lesson.course)
\/
= link_to @lesson.title, course_lesson_path(@course, @lesson)
\/
Edit
%p

.card 
  .card-header 
    %h3
      .far.fa-check-square 
      Editing lesson
  .card-body
    = render 'form'
  .card-footer
    = link_to 'Show lesson', course_lesson_path(@course, @lesson)
    \|
    = link_to 'Back to course', course_path(@lesson.course)

app/views/lessons/new.html.haml
- content_for :title do 
  Judo2000 
  \/
  Course
  = @course.title 
  \/
  New lesson

= link_to 'Courses', courses_path
\/
= link_to @course.title, course_path(@course)
\/
New
%p

.card 
  .card-header
    %h3
      .far.fa-check-square
      New lesson
  .card-body
    = render 'form'
  .card-footer
    = link_to 'Back to course', course_path(@course)

app/views/lessons/show.html.haml
- content_for :title do
  Judo2000 
  |
  Courses
  = @course.title
  |
  Lesson
  #{@lesson.row_order_rank + 1}.
  = @lesson.title


= link_to 'Courses', courses_path
= link_to course_path(@lesson.course) do
  .fa.fa-graduation-cap
  = @lesson.course.title
|
= link_to course_lesson_path(@course, @lesson) do
  .fa.fa-check-square
  |#{@lesson.row_order_rank + 1}
  = @lesson.title
%p

/= @lesson.user_lessons.where(user: current_user).first.impressions
.row
  .col-lg-8
    = render 'lessons/lesson', lesson: @lesson
    %p
    %h4
      .fa.fa-comment
      Comments: 
      -# = @comments.count
      = @lesson.comments_count
    .row
    .card  
      .card-header
        Leave a Comment
      .card-body
        = render 'lessons/comments/form'
    %hr
    - @comments.each do |comment|
      = render 'lessons/comments/comment', comment: comment
      %p

  .col-lg-4
    %ul.list-group
      %li.list-group-item
        = link_to course_path(@lesson.course) do
          .fa.fa-graduation-cap
          = @lesson.course.title
        .row
        .fa.fa-spinner
        = number_to_percentage(@course.progress(current_user), precision: 0)

      - @lessons.each do |lesson|
        - if @lesson.present? && lesson == @lesson
          %li.list-group-item.list-group-item-success
            = render 'lessons/lesson_preview', lesson: lesson
        - else
          %li.list-group-item
            = render 'lessons/lesson_preview', lesson: lesson