config/routes.rb
Rails.application.routes.draw do
  
  #devise_for :users
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  
  root 'home#index'
  get 'home/index'
  get 'activity', to: 'home#activity'
  get 'analytics', to: 'home#analytics'
  get 'privacy_policy', to: 'home#privacy_policy'
  
  
  resources :enrollments do 
    get :my_students, on: :collection
    member do 
      get :certificate
    end
  end
  
  resources :tags, only: [:create, :index, :destroy]
  resources :courses do
    get :purchased, :pending_review, :created, :unapproved, on: :collection
    member do 
      get :analytics
      patch :approve
      patch :unapprove
    end
    resources :lessons, escept: [:index] do 
      resources :comments, escept: [:index]
      put :sort 
      member do 
        delete :delete_video
      end
    end
    resources :enrollments, only: [:new, :create]
    resources :course_wizard, controller: 'courses/course_wizard'
  end
  
  
  resources :users, only: [:index, :edit, :show, :update]

  resources :youtube, only: :show
  
  namespace :charts do 
    get 'users_per_day'
    get 'enrollments_per_day'
    get 'course_popularity'
    get 'money_makers'
  end 
  #get 'charts/users_per_day', to: 'charts#users_per_day'
  #get 'charts/enrollments_per_day', to: 'charts#enrollments_per_day'
  #get 'charts/course_popularity', to: 'charts#course_popularity'
  #get 'charts/money_makers', to: 'charts#money_makers'
end

app/controllers/courses/course_wizard_controller.rb
class Courses::CourseWizardController < ApplicationController
  include Wicked::Wizard
  before_action :set_progress, only: [:show, :update]
  before_action :set_course, only: [:show, :update, :finish_wizard_path]

  steps :basic_info, :details, :lessons, :publish

  def show
    authorize @course, :edit?
    case step
    when :basic_info 
    when :details 
      @tags = Tag.all 
    when :lessons
    when :publish
    end
    render_wizard
  end

  def update 
    authorize @course, :edit?
    case step
    when :basic_info
    when :details 
      @tags = Tag.all 
    when :lessons
    when :publish
    end
    @course.update(course_params)
    render_wizard @course
  end

  def finish_wizard_path
    authorize @course, :edit?
    #@course = Course.friendly.find(params[:course_id])
    course_path(@course)
    
  end

  private 

  def set_course 
    @course = Course.friendly.find params[:course_id]
  end
  
  def set_progress
    if wizard_steps.any? && wizard_steps.index(step).present?
      @progress = ((wizard_steps.index(step) + 1).to_d / wizard_steps.count.to_d) * 100
    else
      @progress = 0
    end
  end

  def course_params
    params.require(:course).permit(:title, :description, :short_description, :price, 
      :language, :level, :published, :logo, tag_ids: [],
      lessons_attributes: [:id, :title, :content, :_destroy]
    )
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  skip_before_action :authenticate_user!, :only => [ :show ]
  before_action :set_course, only: [ :show, :edit, :update, :destroy, :approve, :unapprove, :analytics ]

  def index
    # if params[:title]
    #   @courses = Course.where('title LIKE ?', "%#{params[:title]}%") #case sensetive
    # else
      #@courses = Course.all

      # @q = Course.ransack(params[:q])
      # @courses = @q.result.includes(:user)
    # end

    @ransack_path = courses_path

    @ransack_courses = Course.published.approved.ransack(params[:courses_search], search_key: :courses_search)
     #@courses = @ransack_courses.result.includes(:user)
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user, :course_tags, :course_tags => :tag))
    @tags = Tag.all.where.not(course_tags_count: 0).order(course_tags_count: :desc)
  end

  def purchased 
    @ransack_path = purchased_courses_path
    @ransack_courses = Course.joins(:enrollments).where(enrollments: {user: current_user}).ransack(params[:courses_search], search_key: :courses_search)
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user, :course_tags, :course_tags => :tag))
    @tags = Tag.all.where.not(course_tags_count: 0).order(course_tags_count: :desc)
    render 'index'
  end

  def pending_review
    @ransack_path = pending_review_courses_path
    @ransack_courses = Course.joins(:enrollments).merge(Enrollment.pending_review.where(user: current_user)).ransack(params[:courses_search], search_key: :courses_search)
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user))
    @tags = Tag.all.where.not(course_tags_count: 0).order(course_tags_count: :desc)
    render 'index'
  end

  def created
    @ransack_path = created_courses_path
    @ransack_courses = Course.where(user: current_user).ransack(params[:courses_search], search_key: :courses_search)
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user))
    @tags = Tag.all.where.not(course_tags_count: 0).order(course_tags_count: :desc)
    render 'index'
  end

  def unapproved 
    @ransack_path = unapproved_courses_path
    @ransack_courses = Course.unapproved.ransack(params[:courses_search], search_key: :courses_search)
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user, :course_tags, :course_tags => :tag))
    @tags = Tag.all.where.not(course_tags_count: 0).order(course_tags_count: :desc)
    render 'index'
  end

  def approve 
    authorize @course, :approve?
    @course.update_attribute(:approved, true)
    redirect_to @course, notice: "Course approved!"
  end

  def unapprove
    authorize @course, :approve?
    @course.update_attribute(:approved, false)
    redirect_to @course, notice: "Course unapproved and hidden!"
  end
  
  def analytics
    authorize @course, :owner?
  end

  def show
    authorize @course
    @lessons = @course.lessons.rank(:row_order)
    @enrollments_with_reviews = @course.enrollments.reviewed
  end

  def new
    @course = Course.new
    authorize @course
    @tags = Tag.all
  end

  def edit
    authorize @course
    @tags = Tag.all
  end

  def create
    @course = Course.new(course_params)
    authorize @course
    @course.description = 'Curriculum description'
    @course.marketing_description = 'Marketing description'
    @course.user = current_user
    respond_to do |format|
      if @course.save
        format.html { redirect_to course_course_wizard_index_path(@course), notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        @tags = Tag.all
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @course
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        @tags = Tag.all
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @course
    if @course.destroy
      respond_to do |format|
        format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
        format.json { head :no_content }
      end
    else 
      redirect_to @course, alert: "This course has enrollments and cannot be destroyed."
    end
  end

  private
    def set_course
      @course = Course.friendly.find(params[:id])
    end

    def course_params
      params.require(:course).permit(:title, :description, :marketing_description, :price, 
        :language, :level, :published, :logo, tag_ids: [])
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
  def enrollment_button(course)
    if current_user
      if course.user == current_user 
        link_to "Your created this course. View Analytics", course_path(course)
      elsif course.enrollments.where(user: current_user).any?
        link_to course_path(course) do 
          # "You are enrolled in this course, keep learning." + 
          "<i class='fa fa-spinner'></i>".html_safe + " " +
          number_to_percentage(course.progress(current_user), precision: 0)
        end
      elsif course.price > 0
        link_to number_to_currency(course.price), new_course_enrollment_path(course), class: 'btn btn-success'
      else 
        link_to "Free", new_course_enrollment_path(course), class: 'btn btn-success'
      end
      #logic to buy
    else
      link_to "Check price", new_course_enrollment_path(course), class: "btn btn-md btn-success"
    end
  end

  def review_button(course)
    user_course = course.enrollments.where(user: current_user)
    if current_user 
      if user_course.any?
        if user_course.pending_review.any?
          link_to edit_enrollment_path(user_course.first) do
            "<i class='text-warning fa fa-star'></i>".html_safe + " " +
            "<i class='text-dark fa fa-question'></i>".html_safe + " " + 
            "Add a review"
          end
        else 
          link_to enrollment_path(user_course.first) do 
            "<i class='text-warning fa fa-star'></i>".html_safe + " " +
            "<i class='text-success fa fa-check'></i>".html_safe + " " + 
            "Thanks for your review!"
          end
        end
      end 
    end 
  end

  def certificate_button(course)
    user_course = course.enrollments.where(user: current_user)
    if current_user
      if user_course.any?
        if course.progress(current_user) == 100
          link_to certificate_enrollment_path(user_course.first, format: :pdf), class: 'btn btn-sm btn-danger' do
            "<i class='fa fa-file-pdf'></i>".html_safe + " " +
            "Certificate of Completion"
          end
        else
          "Certificate available after completion"
        end
      end
    end
  end
end

app/views/courses/_course.html.haml
.card 
  .card-header 
    .fa.fa-graduation-cap
    = link_to course.title, course_path(course) 
    - if course.logo.present?
      .card-img-top
        = image_tag course.logo.url, height: '200px', width: '100%'
    
  .card-body 
    %small= simple_format(course.marketing_description)
  .card-footer
    .text-center
      = enrollment_button(course)
      .row
      = review_button(course)
      
  .card-footer
    .row
      .col-md-6
        .text-warning.fa.fa-star
        = course.average_rating
        /= course.enrollments.count
        %b= course.enrollments_count
        (
        .fa.fa-user-graduate 
        = course.enrollments_count
        )
        /= course.average_rating
        /- @rating = course.average_rating
        /- @rating.times do
        /  .text-warning.fa.fa-star
        .fa.fa-tasks 
        = course.lessons_count
      .col-md-6 
        .text-right
          .fa.fa-chalkboard-teacher
          = link_to course.user.username, user_path(course.user)
  -# .card-footer 
     

  -# .card-footer 
  -#   .row 
  -#     .col-md-6
  -#       .fa.fa-globe-americans 
  -#       = course.language 
  -#     .col-md-6 
  -#       .text-right
  -#         .fa.fa-signal
  -#         = course.level
  
  - if current_user
    - if policy(course).owner?
      .card-footer
        = link_to 'Add lesson', new_course_lesson_path(course, @lesson), class: 'btn btn-primary btn-sm mr-1'
        = link_to course_course_wizard_index_path(course), class: "btn btn-sm btn-warning mr-1" do 
          .fa.fa-edit 
          Edit
        - if policy(course).destroy?
          = link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger'
        = link_to analytics_course_path(course), class: 'btn btn-sm btn-info' do
          .fa.fa-chart-bar
          Analtycs
    - if policy(course).admin_or_owner?
      .card-footer
        - if course.published?
          .badge.badge-success published
        - else
          .badge.badge-danger unpublished
        - if course.approved?
          .badge.badge-success approved
        - else
          .badge.badge-danger unapproved
    - if policy(course).approve?
      .card-footer
        - if course.approved?
          = link_to 'unapprove', unapprove_course_path(course), method: :patch, class: 'btn btn-sm btn-danger'
        - else
          = link_to 'approve', approve_course_path(course), method: :patch, class: 'btn btn-sm btn-success'
  .card-footer 
    - course.tags.each do |tag| 
      .badge.badge-info
        = tag.name

app/views/courses/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@course) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
    
  .form-actions
    = f.button :submit

app/views/courses/analytics.html.haml
- content_for :title do
  Corsego 
  |
  = @course.title
  Analtycs

= link_to 'Courses', courses_path
|
= link_to course_path(@course) do
  .fa.fa-graduation-cap
  = @course.title
|
= link_to analytics_course_path(@course) do
  .fa.fa-chart-bar
  Analtycs

/%h4.text-center 
/  Analtycs for #{@course.title}
%h4.text-center
  Enrollments per day, quantity
= line_chart @course.enrollments.group_by_day(:created_at).count

%h4.text-center
  Enrollments per day, revenue
= line_chart @course.enrollments.group_by_day(:created_at).sum(:price)

%h4.text-center
  Unique user views (how many unique users viewed the lesson)
= bar_chart @course.user_lessons.joins(:lesson).group(:'lessons.title').count

%h4.text-center
  Impressions per lesson (how many times the lesson was opened)
= bar_chart @course.user_lessons.joins(:lesson).group(:'lessons.title').sum(:impressions)

app/views/courses/edit.html.haml
 - content_for :title do
  Judo2000 
  \| 
  Editing course
  = @course.title

= link_to 'Courses', courses_path
|
.fa.fa-graduation-cap
= link_to course_path(@course) do
  = @course.title
|
= link_to edit_course_path(@course) do
  Edit

.card
  .card-header
    %h3
      .fa.fa-graduation-cap
      Editing course
  .card-body
    = render 'form'
  .card-footer
    = link_to 'Cancel', @course
.card 
  .card-header 
    %h3 
      .fa.fa-graduation-cap
      Editing course
  .card-body 
    = render 'form'
  .card-footer
    = link_to 'Show', @course
    \|
    = link_to 'Back', courses_path

app/views/courses/index.html.haml
- content_for :title do 
  Judo2000 
  \|
  = action_name.humanize
  courses

%h3
  .text-center
    = action_name.humanize
    Courses 
    .badge.badge-info 
      = @courses.count 
%p
.row 
  .col-md-2 
    = search_form_for @ransack_courses, as: :courses_search, url: @ransack_path do |f|
      /= search_form_for @q do |f|
      = f.label :title
      = f.search_field :title_cont, placeholder: 'Title', class: 'form-control form-controll-sm'
      = f.label :tag 
      = f.search_field :course_tags_tag_name_cont, placeholder: 'Tag name', class: 'form-control form-control-sm'

      = f.label :description
      = f.search_field :marketing_description_cont, placeholder: 'Description', class: 'form-control form-controll-sm'
      /= f.search_field :language_cont, placeholder: 'Language', class: 'form-control form-controll-sm'
      = f.label :language
      = f.select :language_cont, Course.languages, include_blank: true, class: 'form-control form-controll-sm'
      = f.label :level
      = f.select :level_cont, Course.levels, include_blank: true, class: 'form-control form-controll-sm'
      /= f.search_field :level_cont, placeholder: 'Level', class: 'form-control form-controll-sm'
      /= f.label :price
      = sort_link(@ransack_courses, :price)
      = f.search_field :price_eq, placeholder: 'Price', class: 'form-control form-controll-sm'
      = f.label :teacher
      = f.search_field :user_email_cont, placeholder: 'user email', class: 'form-control form-controll-sm'
      .row
      = sort_link(@ransack_courses, :average_rating, "Top Rated")
      .row 
      = sort_link(@ransack_courses, :enrollments_count, "Popular")
      .row 
      = sort_link(@ransack_courses, :created_at, "Fresh")
      .row
      = f.submit
    = link_to @ransack_path, class: 'btn btn-sm btn-secondary' do 
      .fa.fa-sync
    .p-2
    .row 
    - @tags.all.each do |tag|
      -# = link_to courses_path(courses_search: {course_tags_tag_id_eq: tag.id}) do
      = link_to controller: controller_name, action: action_name, courses_search: {course_tags_tag_id_eq: tag.id} do
        .badge.badge-info 
          = tag.name 
          = tag.course_tags_count

  .col-lg-10
    .card-columns
      - @courses.each do |course|
        = render 'courses/course', course: course
    /!= pagy_nav(@pagy)
    != pagy_bootstrap_nav(@pagy)
%br

app/views/courses/new.html.haml
- content_for :title do 
  Judo2000 
  \|
  New course
.card
  .card-header
    %h3 
      .fa.fa-graduation-cap
      New course
  .card-body
    = render 'form'
  .card-footer
    = link_to 'Back to courses', courses_path

app/views/courses/show.html.haml
- content_for :title do
  Judo2000 
  |
  = @course.title

= link_to 'Courses', courses_path
|
= link_to course_path(@course) do
  .fa.fa-graduation-cap
  = @course.title

.row
  .col-lg-8.order-1.order-lg-1
    .jumbotron
      %h3
        .fa.fa-graduation-cap
        = @course.title
        -# .row
        -# - if @course.logo.attached?
        -#   = image_tag @course.logo, width: '200px'
          
        /.row
        /HAS AVATAR?
        /= @course.logo.attached?
        /- if @course.avatar.attached?
        /  = image_tag @course.avatar, width: "200px"
      %hr
      .fa.fa-clock
      Created
      = @course.created_at.strftime("%m/%Y")
      .row
      .fa.fa-clock
      Last updated
      = @course.updated_at.strftime("%m/%Y")
      .row
      .fa.fa-globe-africa
      = @course.language
      .row
      .fa.fa-signal
      = @course.level
      %hr
      = @course.description

    %h4
      .fa.fa-tasks
      = pluralize(@course.lessons_count, 'lesson')
      /Lessons:
      /= @course.lessons_count
      .float-right
        .fa.fa-spinner
        = number_to_percentage(@course.progress(current_user), precision: 0)
        = certificate_button(@course)
    .list-group.lesson-sortable
      - @lessons.each do |lesson|
        = content_tag "div", id: "lesson-#{lesson.id}", data: { model_name: lesson.class.name.underscore, update_url: course_lesson_sort_path(@course, lesson)} do
          .list-group-item
            .fa.fa-sort.all-scroll{:style => "cursor: grab; height: 60px;"}
            = render 'lessons/lesson_preview', lesson: lesson
    %p

    

  .col-lg-4.order-0.order-lg-1
    .sticky-top
      = render 'courses/course', course: @course
    %p

%h4 Similar Courses 
= @course.tags.pluck(:id)
.row
- Course.all.where.not(id: @course.id).each do |course|
  - unless @course.tags.pluck(:id).intersection(course.tags.pluck(:id)).count.zero?
    .card-columns
      = render 'courses/course', course: course